name: Automated iOS Build

on:
  push:
    branches:
      - "main"
      - "release/*"
    tags:
      - "build-ci*"
      - "release*"

jobs:
  build:
    runs-on: macos-26
    steps:
    - uses: actions/checkout@v3
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '26.0'
    - name: Download Missing iOS Simulator Components
      run: |
        sudo xcodebuild -downloadPlatform iOS
    - uses: yukiarrr/ios-build-action@v1.11.2
      with:
        project-path: qBitControl.xcodeproj
        p12-base64: ${{ secrets.P12_BASE64 }}
        mobileprovision-base64: ${{ secrets.MOBILEPROVISION_BASE64 }}
        code-signing-identity: ${{ secrets.CODE_SIGNING_IDENTITY }}
        team-id: ${{ secrets.TEAM_ID }}
        output-path: qBitControl.ipa
    - name: Extract Version and Build Number
      if: startsWith(github.ref, 'refs/tags/')
      id: extract_version
      run: |
        TAG="${GITHUB_REF#refs/tags/}"
        echo "Full Tag: $TAG"
        if [[ "$TAG" == build-ci-* ]]; then
          WITHOUT_PREFIX="${TAG#build-ci-}"
          VERSION="${WITHOUT_PREFIX%-*}"
          BUILD_NUMBER="${WITHOUT_PREFIX##*-}"
        elif [[ "$TAG" == release-* ]]; then
          VERSION="${TAG#release-}"
          BUILD_NUMBER=""
        else
          echo "Unknown tag pattern: $TAG"
          exit 1
        fi
        echo "Extracted Version: $VERSION"
        echo "Extracted Build Number: $BUILD_NUMBER"
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "BUILD_NUMBER=$BUILD_NUMBER" >> $GITHUB_ENV
    - name: "Update Release"
      if: startsWith(github.ref, 'refs/tags/')
      uses: "softprops/action-gh-release@v2"
      with:
        tag_name: ${{ github.ref_name }}
        prerelease: ${{ !startsWith(github.ref, 'refs/tags/release-') }}
        name: "qBitControl ${{ env.VERSION }}${{ env.BUILD_NUMBER != '' && format(' ({0})', env.BUILD_NUMBER) || '' }}"
        files: |
          qBitControl.ipa
